### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by sni** [esimonov/ifshort#2] opened 2021-01-26 13:44 UTC
ifshort complains about a waitgroup beeing used only once but in fact it is used multiple times afterwards:

```
lmd/listener.go:208:2: variable 'wg' is only used in the if-statement (lmd/listener.go:222:2); consider using short syntax (ifshort)
        wg := &sync.WaitGroup{}
```

```
func SendCommands(commandsByPeer map[string][]string) (code int, msg string) {
	code = 200
	msg = "OK"
	resultChan := make(chan error, len(commandsByPeer))
	wg := &sync.WaitGroup{}
	for pID := range commandsByPeer {
		PeerMapLock.RLock()
		p := PeerMap[pID]
		PeerMapLock.RUnlock()
		wg.Add(1)
		go func(peer *Peer) {
			defer logPanicExitPeer(peer)
			defer wg.Done()
			resultChan <- peer.SendCommandsWithRetry(commandsByPeer[peer.ID])
		}(p)
	}

	if waitTimeout(wg, PeerCommandTimeout) {
		code = 202
		msg = "sending command timed out but will continue in background"
		return
	}
...
}
```

Original code can be found here:
https://github.com/sni/lmd/blob/f6eefbe1af8012d29998e122441c3c705d648a3d/lmd/listener.go#L204

**Comment by esimonov** [comment] 2021-01-26 16:28
Hello @sni and thank you for your interest!
I appreciate your effort of submitting a PR with a new test case, but as it turned out, this false positive warning has nothing specific to do with waitgroups; it was caused by the assignment to a pointer, which cannot be shortened. Therefore, this test case should be sufficient to cover your use case - https://github.com/esimonov/ifshort/commit/f4c7e24b187bf76782f2277ef9585bff478327ba#diff-57ce4993559e6d59201b14d9309889cf5ce53e1d7e3107683fa30a1a25782a49

**Comment by sni** [comment] 2021-01-26 16:31
no worries, just wanted to make it easier to reproduce. Yours is definitly better.

**Comment by sni** [comment] 2021-01-26 17:08
thanks for fixing this so quick

**Comment by jpreese** [comment] 2021-01-26 21:32
A really dumb example, but I assume @sni's issue is the same as this one?

```golang
	ctxValue := ctx.Value("foo")
	if ctxValue == nil {
		panic("no foo!")
	}

	otherCtx, ok := ctxValue.(*context.Context)
	if !ok {
		panic("no ctx!")
	}

	return
```

```text
variable 'ctxValue' is only used in the if-statement (xxx); consider using short syntax (ifshort)
        ctxValue := ctx.Value("foo")
```

Where `ctx.Value` returns `interface{}` (which is a pointer due to `interface` shenanigans)

**Comment by esimonov** [comment] 2021-01-27 16:13
Hello @jpreese , thanks for joining us!
In fact, it is yet another case that wasn't properly handled. 
It's now fixed in https://github.com/esimonov/ifshort/commit/113a74d19ea0ee25cc342b28ca7c8895b7ce64b8.

**Comment by jpreese** [comment] 2021-01-27 17:39
Oh perfect, thanks!

**Closed** 2021-01-30 15:24 UTC
